version: "2.4"

services:

  etcdio-test:
    image: quay.io/coreos/etcd:v3.5.4
    restart: unless-stopped
    volumes:
      - "./volumes/${DATADIR_PREFIX:-.}/etcd-data:/etcd-data:rw"
    networks:
      - etcdio
    ports:
      - "8989:2379"
    command: >
      /usr/local/bin/etcd
      --name backendai-etcd
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://0.0.0.0:2379
      --enable-v2=true
      --auto-compaction-retention 1
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  etcdio:
